version: '3'

services:
  app:
    container_name: node_adasi_api
    build: .
    ports: 
      - "3000:3000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://$DB_USER:$DB_PASSWORD@adasi_postgres:5432/$DB_NAME
    volumes:
      - .:/usr/app
    depends_on:
      - postgres
  
  postgres:
    image: postgres:15.4
    container_name: adasi_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: adasi_db